
#nodejs image
FROM node:20.16-alpine3.19

# setting my linux working directory
WORKDIR /ussd

# Copy the package.json file to be use by node package manager
COPY package*.json ./


# Intall application dependecies
RUN npm install

#Copy the rest of the application
COPY . .

# Expose the port the app is running on
EXPOSE  8888

CMD [ "node" , "server.js" ]



